MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "../pretrained_models/fastercnnmodel_no_last_layers.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("cocohead_train",)
  TEST: ("cocohead_test", "cocohead_train")
DATALOADER: 
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.0002
  MAX_ITER: 3000 # 20 * NUM_IMAGES
  IMS_PER_BATCH: 8
  STEPS: (1000, 1500)
  CHECKPOINT_PERIOD: 500
TEST:
  IMS_PER_BATCH: 8
OUTPUT_DIR: "frame"